[package]
name = "Rust"
version = "0.1.0"
authors = ["buffosens <buffo@luppis.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1.1"
nom = "5"
rand = "0.5.5"
